### ISSUE TITLE
Admin Panel Docker problem

### ISSUE THREAD

**Issue by abrousseau89** [g3w-suite/g3w-admin-frontend#5]
Hello, 

i need to test the admin panel.

My first install is with Docker

When i type : 

`python3 manage.py makemigrations frontend
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
No changes detected in app 'frontend'

root@4dbe27b81e3a:/code/g3w-admin# python3 manage.py migrate frontend
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"
CommandError: App 'frontend' does not have migrations.

root@4dbe27b81e3a:/code/g3w-admin# python3 manage.py collectstatic --noinput
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
"Loading native module /usr/lib/qgis/server/libdummy.so"
"Loading native module /usr/lib/qgis/server/liblandingpage.so"
"Loading native module /usr/lib/qgis/server/libwcs.so"
"Loading native module /usr/lib/qgis/server/libwfs.so"
"Loading native module /usr/lib/qgis/server/libwfs3.so"
"Loading native module /usr/lib/qgis/server/libwms.so"
"Loading native module /usr/lib/qgis/server/libwmts.so"

0 static files copied to '/shared-volume/static', 7874 unmodified.
`
i have errors  ? 
After, I can't find or type the following code

`...
FRONTEND = True
FRONTEND_APP = 'frontend'
...`

So I'm stuck to finish the installation.

And in my settings_docker.py, i have two times same code, normal ??

`G3WADMIN_PROJECT_APPS = []

G3WADMIN_LOCAL_MORE_APPS = [
    'editing',
    'caching',
    'filemanager',
    'qplotly',
    'openrouteservice',
    'qtimeseries',
    'frontend'

G3WADMIN_PROJECT_APPS = []

G3WADMIN_LOCAL_MORE_APPS = [
    'editing',
    'caching',
    'filemanager',
    'qplotly',
    'openrouteservice',
    'qtimeseries',
    'frontend'
]

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'g3w-suite',
        'USER': 'docker',
        'PASSWORD': 'docker',
        'HOST': 'postgis',
        'PORT': '5432',
    }
}

`

Thanks

**Comment by wlorenzetti** [comment]
@abrousseau89 it seams all correct, now can you see the frontend app?

**Comment by abrousseau89** [comment]
Good morning,

no it doesn't work. Impossible to have the interface despite all the manipulations.

**Comment by abrousseau89** [comment]
Ok it's good I retry the manipulations again and everything works. 

I don't know why but I had forgotten to do the following manipulation at the start

`docker-compose up -d`

Good now ! Thanks
